name: tots_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0-269.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  equatable: ^2.0.3  
  dartz: ^0.10.0
  intl: ^0.19.0
  phosphor_flutter: ^2.0.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/assets/images/png/